### ISSUE TITLE
plan

### ISSUE THREAD

**Issue by AceBear** [InCar/rooster-shared#1]
![arch](https://docs.google.com/drawings/d/1AWuwUzewYDmQvU6i9eSLcMV_DH3sBJU9m-l6g2p7t0k/pub?w=960&h=720)

# G based on AliYun
基于阿里云的数据采集服务
5月31日~6月10日
1. 基本的设备模拟器
2. 数据采集逻辑
3. 蓝度V3.20协议头解析
4. 阿里云MQ

# P based on AliYun
基于阿里云的数据处理分析服务

# T based on AliYun
基于阿里云的数据转换服务

**Comment by aaric** [comment]
已久远，关闭
