### ISSUE TITLE
分析失败原因

### ISSUE THREAD

**Issue by AceBear** [InCar/rooster-shared#67]
```
2017-06-06 17:56:53.590 [pool-4-thread-2] INFO  gather.DataPachReadTask - no packs!!
```

@xiaozhou010 认为发送了正确格式的数据包
但解析程序没有解出数据

分析原因

@youbeiwuhuan @aaric

**Comment by aaric** [comment]
昨天发现mns endpoint地址配置成了内网地址，导致发送消息timeout，改成外网地址可以正常发送消息

@AceBear

**Comment by youbeiwuhuan** [comment]
无需更改代码
