### ISSUE TITLE
让 DataTarget继承自DataPack

### ISSUE THREAD

**Issue by AceBear** [InCar/rooster-shared#93]
我们定义`DataPack`是从数据包协议中解析出来的对象
所有涉及从协议中解析出来的对象，皆继承自DataPack

所以，现在让 DataTarget继承自DataPack
所有DataTargetXXX也都相应的改名为DataPackXXX

删除掉 ETargetType 枚举，它没有存在的必要

重新考虑 DataTarget 中的成员变量，不要按蓝度数据包的思维来组织它
比如obdCode，其它协议根本就不存在obdcode一说

**Comment by aaric** [comment]
已解决
